### ISSUE TITLE
cannot build with pre-installed external dependencies.

### ISSUE THREAD

**Issue by ronyb29** [Comcast/cjwt#15]
When trying to build as part of a bundle, cjwt always downloads trower-base64 and cJSON and uses a fixed version.

In the case of trying to have cjwt as a dependency from a bigger project the project will have to link trower-base64 and cJSON too, so it will need to install them. When trying to compile like this, it would be beneficial to look for libraries in the same prefix cjwt will be installed in.

**Comment by schmidtw** [comment]
My CMake skills are a bit weak.  I think there is a way to do this, but I'm not sure.

**Comment by schmidtw** [comment]
I think we have addressed a significant number of the issues with dependencies in the 1.0.4 release.
