### ISSUE TITLE
Unable to build cjwt in ubuntu 20.04 with meson 0.53.2

### ISSUE THREAD

**Issue by pkumarex** [Comcast/cjwt#55]
Getting the error, fallback must contain exactly two items.

```
The Meson build system
Version: 0.53.2
Source dir: /home/isecl-ami2/setup/cjwt
Build dir: /home/isecl-ami2/setup/cjwt/build
Build type: native build
Project name: cjwt
Project version: 2.1.0
C compiler for the host machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring cjwtver.h using configuration
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency openssl found: YES 1.1.1f

meson.build:35:0: ERROR: Fallback info must have exactly two items.

A full log can be found at /home/isecl-ami2/setup/cjwt/build/meson-logs/meson-log.txt
```

After adding, two items in fallback manually. Getting the following error eventhough trewor package is installed.

trower-base64 not found and it shows dependency not satisfied during build.

**Comment by schmidtw** [comment]
This might help get you over your meson issues: https://github.com/xmidt-org/cjwt/compare/main...add-2nd-param  I'm traveling and don't have much time to dig into this right now.  I probably won't for a month or two.

I'm not able to build using 1.1.1x openssl & the library needs to be ported to 3.x.

You might also try using 1.0.1 or newer meson.  I am using that & didn't have the issues you experienced.

**Comment by kvijay1918** [comment]
This is not resolving the issue.

**Comment by schmidtw** [comment]
I think you need a newer version of meson.  I would recommend 1.x.x or newer.  If it is still a problem with that version please open an issue.

**Comment by schmidtw** [comment]
I specifically added a ubuntu 20.04 github build that works.
